In [2]:
#기본적인 torch array
import numpy as np
import torch
import matplotlib.pyplot as plt


t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [2.,3.,4.]])
                    

print(t.dim())
print(t.size())
print(t[:,1])
print(t[:,1].size())
print((t[:,:-1]))


2
torch.Size([3, 3])
tensor([2., 5., 3.])
torch.Size([3])
tensor([[1., 2.],
        [4., 5.],
        [2., 3.]])


In [3]:
#same sHape

m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[1,2]])

print(m1 + m2)

k =  10

print(m1 + k)
# broad casting
m3 = torch.Tensor([[3],
                  [4]])

print(m1 + m3)
 

tensor([[4., 5.]])
tensor([[13., 13.]])
tensor([[6., 6.],
        [7., 7.]])


In [4]:
##mat mul

m1 = torch.Tensor([[1,2],[3,4]])
m2 = torch.Tensor([[1],
                   [2]])

print("m1 shape: ", m1.shape)
print("m2 shape: ", m2.shape)

m3 = m1.matmul(m2)
print("matmul:" ,m3)



## matmul 을 쓰지 않고 * 연산자와 mul 연산자를 쓰는 경우, broadcasting되어 dot product를 수행한다.
m3dot= m1*m2
print(m3dot)

m3mul = m1.mul(m2)

print(m3mul)


m1 shape:  torch.Size([2, 2])
m2 shape:  torch.Size([2, 1])
matmul: tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [5]:
## 그냥 연산들

t = torch.FloatTensor([1,2])
print("Mean")
print(t.mean())


#Axis mean
t = torch.FloatTensor([[1,2,3,],
                       [4,5,6]])

print("Axis 0")
print(t.mean(dim= 0))
print(t.sum(dim = 0))

print("Axis 1")
print(t.mean(dim = 1))
print(t.sum(dim = 1))


print("Axis = -1")
print(t.mean(dim = -1))

##dim, axis가 외우기 어려우면 다음과 같이 생각하자
##0차원부터 시작한다고 하고, 0차원이 그냥 1행 n열이라고 한다면, 이게 기준으로 sum이 된다는건,결국 열로써 더해진다고 생각해라
#-1 은 왜 0이랑 똑같지? 




Mean
tensor(1.5000)
Axis 0
tensor([2.5000, 3.5000, 4.5000])
tensor([5., 7., 9.])
Axis 1
tensor([2., 5.])
tensor([ 6., 15.])
Axis = -1
tensor([2., 5.])


In [6]:
a1 = np.array([[1,2,3],
               [2,3,4]])

print("Axis = 0")
print(np.mean(a1,axis = 0))

print("Axis = 1")
print(np.mean(a1,axis = 1))



Axis = 0
[1.5 2.5 3.5]
Axis = 1
[2. 3.]


In [7]:
#max와 argmax

t = torch.Tensor([[1,2],[4,3]])

print(t)

print(t.max())
print(t.argmax())


print("MAx: dim = 0 ", t.max(dim = 0) )
print("argmax axis 0",t.argmax(dim = 0))


print("MAx: dim = 1 ", t.max(dim = 1) )
print("argmax axis 1",t.argmax(dim = 1))




tensor([[1., 2.],
        [4., 3.]])
tensor(4.)
tensor(2)
MAx: dim = 0  torch.return_types.max(
values=tensor([4., 3.]),
indices=tensor([1, 1]))
argmax axis 0 tensor([1, 1])
MAx: dim = 1  torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 0]))
argmax axis 1 tensor([1, 0])


In [8]:
#np = reshape, torch = view

#먼저, np랑 torch랑 서로 어느정도 연동이 되는듯?

a = np.array([[[1, 2, 3],
               [4, 5, 6]],
              [[7, 8, 9],
               [10, 11, 12]]])

# ==> tensor로 변환

d = torch.tensor(a)

print(d.shape)


# 여기서 -1 을 넣는것은 앞쪽의 나머지 차원을 하나의 차원으로 묶어버리고, 전부 풀어버리겠다는 거다.
print(d.view([-1]))
print(d.view([-1]).shape)


print(d.view([-1,3]))
print(d.view([-1,3]).shape)


print(d.view([-1,1,3]))
print(d.view([-1,1,3]).shape)


torch.Size([2, 2, 3])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
torch.Size([4, 3])
tensor([[[ 1,  2,  3]],

        [[ 4,  5,  6]],

        [[ 7,  8,  9]],

        [[10, 11, 12]]])
torch.Size([4, 1, 3])


In [ ]:
## Tensor manipulation2
##1. view // reshaping

t = np.array([[[0,1,2],[3,4,5]]],[[[6,7,8],[9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

# -1은 나머지 차원을 전부 풀어버리겠다는 의미
print(ft.view([-1,3])) ## 2 2 3 => 4 3
print(ft.view([-1,3]).shape)

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [13]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [2]:
# squeeze
import torch
x = torch.FloatTensor([[10],[12],[13]])
print(x)
print(x.shape)

print(x.squeeze())
print(x.squeeze().shape)

# unsqueeze
x = torch.FloatTensor([10,12,13])
print(x)
print(x.shape)

print(x.unsqueeze(0))
print(x.unsqueeze(0).shape)


tensor([[10.],
        [12.],
        [13.]])
torch.Size([3, 1])
tensor([10., 12., 13.])
torch.Size([3])
tensor([10., 12., 13.])
torch.Size([3])
tensor([[10., 12., 13.]])
torch.Size([1, 3])


In [3]:
# type casting
#long, float, double
lt = torch.LongTensor([1,2,3,4])
print(lt)

print(lt.float())

bt = torch.ByteTensor([True,False,False,True])
print(bt)

print(bt.long())
print(bt.float())


tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [4]:
#CONCATENATION
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

print(torch.cat([x,y],dim = 0))
print(torch.cat([x,y],dim = 1))

#stacking
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim = 1))


tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
# stack
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))


# ones_like, zeros_like
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

print(torch.ones_like(x))
print(torch.zeros_like(x))



tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# In-place operation
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)



tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


In [ ]:
# linear regression
import torch

x = torch.FloatTensor([[1], [2], [3]])
y = torch.FloatTensor([[2], [4], [6]])

w = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

#torch 에서 간단하게 SGD 사용하기.

optimizer = torch.optim.SGD([w,b], lr = 0.01) # optimizer SGD or Adam or RMSprop 중 선택하기.
for i in range(10):
    hypothesis = x*w + b
    cost = torch.mean((hypothesis - y) ** 2)
    optimizer.zero_grad() # 이거 안하면, 기존의 gradient에 더해져서, 값이 더욱 누적되어버린다. 즉, 이전의 gradient가 새로운 계산에 영향을 끼친다.
    cost.backward() # 이거 하면, w.grad, b.grad에 gradient가 저장된다.
    # print(optimizer.zero_grad())
    optimizer.step() # 이거 하면, w, b에 gradient가 적용된다.
    # print(optimizer.step())
print(w,b)


tensor([1.1663], requires_grad=True) tensor([0.4922], requires_grad=True)
